Minimal fixes to vbht_builder

diff --git a/vbht_builder b/vbht_builder
--- a/vbht_builder
+++ b/vbht_builder
@@ -53,7 +53,7 @@ tempfile=$(mktemp); readonly tempfile
 tar -cJf "$tempfile" 'agplv3' 'openx' 'vbht' 'vbht_uninstaller' 'vbht.udev' 'vbht.logrotate' 'vbht.sudoers' 'vbht.powerbtn.sh' 'vbht.sleepbtn.sh' 2> /dev/null
 
 # calculate the checksum
-checksum=$(sha512sum -b "$tempfile" 2> /dev/null | cut -d' ' -f1); readonly checksum
+checksum=$(sha512sum -b "${tempfile}" 2> /dev/null | cut -d' ' -f1); readonly checksum
 
 # replace checksum into stub, and place it in the destination file
 echo "${stub//___COMPRESSED_DATA_SHA512_CHECKSUM_GOES_HERE___/$checksum}" > "vbht_installer"
@@ -61,7 +61,7 @@ echo "${stub//___COMPRESSED_DATA_SHA512_CHECKSUM_GOES_HERE___/$checksum}" > "vbh
 # append the base64 encoding of the compressed data
 #  (this is in order to avoid problems with "text mode" vs "binary mode" in some
 #   scenarios)
-base64 -w0 -- "$tempfile" >> 'vbht_installer' 2> /dev/null
+base64 -w0 -- "${tempfile}" >> 'vbht_installer' 2> /dev/null
 
 # fix permissions
 chmod a=rx 'vbht_installer'
@@ -70,7 +70,7 @@ chmod a=rx 'vbht_installer'
 tar -cJf 'vbht_source.tar.xz' 'agplv3' 'openx' 'vbht' 'vbht_uninstaller' 'vbht.udev' 'vbht.logrotate' 'vbht.sudoers' 'vbht.powerbtn.sh' 'vbht.sleepbtn.sh' 'vbht_builder' 2> /dev/null
 
 # remove the temporary file
-rm -f -- "$tempfile"
+rm -f -- "${tempfile}"
 
 
 # 'twas a good day :)
@@ -129,22 +129,22 @@ declare tempdir=''
 # ==============================================================================
 
 # fail if the user is not running the script as root
-if (( $UID )); then echo 'Error: this script MUST be run as root!' >&2; exit 1; fi
+if (( UID )); then echo 'Error: this script MUST be run as root!' >&2; exit 1; fi
 
 # fail if we couldn't find "vboxusers" group
-if (( $vbuGID == -1 )); then echo $'Error: could not find `vboxusers\' group!' >&2; exit 1; fi
+if (( vbuGID == -1 )); then echo $'Error: could not find `vboxusers\' group!' >&2; exit 1; fi
 
 # fail if we couldn't find the compressed data's start
-if (( $offset == -1 )); then echo 'Error: could not find data start -- corrupted file!' >&2; exit 1; fi
+if (( offset == -1 )); then echo 'Error: could not find data start -- corrupted file!' >&2; exit 1; fi
 
 # create a new temporary file for the compressed data
 tempfile=$(mktemp); readonly tempfile
 
 # splice the compressed data into the temporary file, and get its checksum
-checksum=$(tail -n+$(( $offset + 1 )) "$0" | base64 -d | tee "$tempfile" | sha512sum -b | cut -d' ' -f1); readonly checksum
+checksum=$(tail -n+$(( offset + 1 )) "$0" | base64 -d | tee "${tempfile}" | sha512sum -b | cut -d' ' -f1); readonly checksum
 
 # if they don't match, give an error
-if [[ "$checksum" != '___COMPRESSED_DATA_SHA512_CHECKSUM_GOES_HERE___' ]]; then echo 'Error: consistency check failed!' >&2; exit 2; fi
+if [[ "${checksum}" != '___COMPRESSED_DATA_SHA512_CHECKSUM_GOES_HERE___' ]]; then echo 'Error: consistency check failed!' >&2; exit 2; fi
 
 
 # ==============================================================================
@@ -185,7 +185,7 @@ EOM
     echo
 
     # if anything other that "Y" was entered, exit
-    if [[ "$REPLY" != 'Y' ]]; then
+    if [[ "${REPLY}" != 'Y' ]]; then
       echo
       echo 'Aborted by user!'
       exit
@@ -202,7 +202,7 @@ fi
 tempdir=$(mktemp -d); readonly tempdir
 
 # extract the data to the newly created tempdir
-tar -xJC "$tempdir" -f "$tempfile" 2> /dev/null
+tar -xJC "${tempdir}" -f "${tempfile}" 2> /dev/null
 
 # -- Final copying -------------------------------------------------------------
 
@@ -214,11 +214,11 @@ if [[ -f '/etc/acpi/powerbtn.sh' ]]; then mv -nT -- '/etc/acpi/sleepbtn.sh' '/et
 #  - udev rules file to "/etc/udev/rules.d"
 #  - logrotate config file to "/etc/logrotate.d"
 #  - sudoers config file to "/etc/sudoers.d"
-mv -fT -- "$tempdir/vbht.powerbtn.sh" '/etc/acpi/powerbtn.sh'        2> /dev/null
-mv -fT -- "$tempdir/vbht.sleepbtn.sh" '/etc/acpi/sleepbtn.sh'        2> /dev/null
-mv -fT -- "$tempdir/vbht.udev"        '/etc/udev/rules.d/vbht.rules' 2> /dev/null
-mv -fT -- "$tempdir/vbht.logrotate"   '/etc/logrotate.d/vbht'        2> /dev/null
-mv -fT -- "$tempdir/vbht.sudoers"     '/etc/sudoers.d/vbht'          2> /dev/null
+mv -fT -- "${tempdir}/vbht.powerbtn.sh" '/etc/acpi/powerbtn.sh'        2> /dev/null
+mv -fT -- "${tempdir}/vbht.sleepbtn.sh" '/etc/acpi/sleepbtn.sh'        2> /dev/null
+mv -fT -- "${tempdir}/vbht.udev"        '/etc/udev/rules.d/vbht.rules' 2> /dev/null
+mv -fT -- "${tempdir}/vbht.logrotate"   '/etc/logrotate.d/vbht'        2> /dev/null
+mv -fT -- "${tempdir}/vbht.sudoers"     '/etc/sudoers.d/vbht'          2> /dev/null
 # change ownership
 chown -f root:root '/etc/acpi/powerbtn.sh' '/etc/acpi/sleepbtn.sh' '/etc/udev/rules.d/vbht.rules' '/etc/logrotate.d/vbht' '/etc/sudoers.d/vbht' 2> /dev/null
 # change permissions
@@ -230,7 +230,7 @@ chmod -f u=rwx,go=rx '/etc/acpi/powerbtn.sh' '/etc/acpi/sleepbtn.sh' 2> /dev/nul
 mkdir -p '/opt/vbht'
 
 # copy the rest of the files to "/opt/vbht"
-mv -ft '/opt/vbht' -- "$tempdir/agplv3" "$tempdir/openx" "$tempdir/vbht" "$tempdir/vbht_uninstaller"
+mv -ft '/opt/vbht' -- "${tempdir}/agplv3" "${tempdir}/openx" "${tempdir}/vbht" "${tempdir}/vbht_uninstaller"
 # change ownership
 chown -f root:vboxusers '/opt/vbht/agplv3' '/opt/vbht/openx' '/opt/vbht/vbht' 2> /dev/null
 # change permissions
@@ -246,8 +246,8 @@ touch '/var/log/vbht/vbht'; chown -f root:vboxusers '/var/log/vbht/vbht'; chmod 
 
 
 # remove temporary file and dir
-rm  -f -- "$tempfile"
-rm -rf -- "$tempdir"
+rm  -f -- "${tempfile}"
+rm -rf -- "${tempdir}"
 
 
 # 'twas a good day :)
